name: flutter_image_picker_ui
description: A Flutter package for a UI to pick or take images
version: 1.0.0
homepage: https://github.com/AbdullahAlMamun12/flutter_image_picker_ui
repository: https://github.com/AbdullahAlMamun12/flutter_image_picker_ui
issue_tracker: https://github.com/AbdullahAlMamun12/flutter_image_picker_ui/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  dotted_border: ^3.1.0
  flutter:
    sdk: flutter
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/upload.png
    - assets/gallery_upload.png
    - assets/camera_outline.png
    - assets/camera_fill.png