name: flutter_image_picker_ui
description: A Flutter package for a UI to pick or take images
author: Abdullah Al Mamun <al-mamun12@hotmail.com>
version: 0.0.1
homepage: https://github.com/AbdullahAlMamun12/flutter_image_picker_ui
repository: https://github.com/AbdullahAlMamun12/flutter_image_picker_ui
issue_tracker: https://github.com/AbdullahAlMamun12/flutter_image_picker_ui/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/upload.png
    - assets/camera.png
  plugin:
    platforms:
      android:
        package: com.al.mamun.flutter_image_picker_ui
        pluginClass: FlutterImagePickerUIPlugin
      ios:
        pluginClass: FlutterImagePickerUIPlugin